# Generated by Django 6.0.7 on 2026-07-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="patronymic",
            field=models.CharField(
                blank=True, help_text="Введите отчество", max_length=100, null=True, verbose_name="Отчество"
            ),
        ),
    ]
