# Generated by Django 6.0.7 on 2026-07-30 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование категории",
                        max_length=150,
                        verbose_name="Наименование категории услуг",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите описание", null=True, verbose_name="Описание категории услуг"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория услуг",
                "verbose_name_plural": "Категории услуг",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите фамилию имя и отчество врача", max_length=150, verbose_name="ФИО"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Введите должность врача",
                        max_length=150,
                        null=True,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        blank=True, help_text="Введите стаж работы", max_length=50, null=True, verbose_name="Стаж"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите категорию",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctors",
                        to="med.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация по врачам",
                "verbose_name_plural": "Информации по врачам",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование услуги", max_length=150, verbose_name="Наименование услуги"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите описание услуги", null=True, verbose_name="Описание услуги"
                    ),
                ),
                ("price", models.FloatField(help_text="Введите цену услуги", verbose_name="Цена")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите категорию",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="med.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_time", models.DateTimeField(verbose_name="Дата и время записи на прием")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активна"), ("cancelled", "Отменена"), ("completed", "Исполнена")],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "result",
                    models.TextField(
                        blank=True,
                        help_text="Введите результат диагностики",
                        null=True,
                        verbose_name="Результат диагностики",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owner_client",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctor_client",
                        to="med.doctors",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="med.services",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на прием",
                "verbose_name_plural": "Записи на прием",
                "ordering": ["owner"],
            },
        ),
    ]
