# Generated by Django 6.0.7 on 2026-07-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "ordering": ["owner", "date_time", "status"],
                "verbose_name": "Запись на прием",
                "verbose_name_plural": "Записи на прием",
            },
        ),
    ]
